# Generated by Django 3.0.6 on 2020-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='Descrição do projeto'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
    ]
