# Generated by Django 3.0.6 on 2020-05-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200527_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
